version: '3.3'
services:
    hrm_fe:
        build:
            context: .
            dockerfile: Dockerfile
        image: vuexy_fe
        container_name: vuexy_fe
        ports:
            - '80:80'
        restart: always
